name: Pruebas de los scripts de 02-flow-control

on:
  push:
    paths:
      - 'scripts/02_flow_control/**/*.sh'

jobs:
  exec-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Ejecutar los scripts dentro de 02-flow-control
        run: |
          find scripts/02_flow_control -type f -name "test-*.sh"| bash

